-- 1. 论坛帖子表 (posts)
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  content text not null,
  image text, -- 可选图片
  likes_count int default 0,
  comments_count int default 0
);

-- 开启 RLS
alter table public.posts enable row level security;

-- 策略：允许所有人查看帖子
create policy "Allow public view posts" on public.posts for select using (true);

-- 策略：允许认证用户发帖
create policy "Authenticated users can create posts" on public.posts 
for insert with check (auth.role() = 'authenticated');

-- 策略：允许用户删除自己的帖子
create policy "Users can delete own posts" on public.posts 
for delete using (auth.uid() = user_id);


-- 2. 论坛评论表 (comments)
create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.posts on delete cascade not null,
  user_id uuid references auth.users not null,
  content text not null
);

-- 开启 RLS
alter table public.comments enable row level security;

-- 策略：允许所有人查看评论
create policy "Allow public view comments" on public.comments for select using (true);

-- 策略：允许认证用户评论
create policy "Authenticated users can create comments" on public.comments 
for insert with check (auth.role() = 'authenticated');


-- 3. 实时聊天室消息表 (chat_messages)
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  content text not null,
  user_email text -- 冗余字段，方便前端显示（也可以通过 join users 表获取，但简单起见存这里）
);

-- 开启 RLS
alter table public.chat_messages enable row level security;

-- 策略：允许认证用户查看聊天记录
create policy "Authenticated users can view chat" on public.chat_messages 
for select using (auth.role() = 'authenticated');

-- 策略：允许认证用户发送消息
create policy "Authenticated users can send chat" on public.chat_messages 
for insert with check (auth.role() = 'authenticated');


-- 4. 私信表 (messages)
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false
);

-- 开启 RLS
alter table public.messages enable row level security;

-- 策略：用户只能查看自己发送或接收的消息
create policy "Users can view own messages" on public.messages 
for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- 策略：用户只能发送给自己以外的人 (sender_id 必须是自己)
create policy "Users can send messages" on public.messages 
for insert with check (auth.uid() = sender_id);


-- 开启 Realtime 监听 (需要在 Supabase Dashboard 的 Replication 设置中开启，或者通过 API)
-- 这里假设已经开启了 public schema 的 replication
-- alter publication supabase_realtime add table public.chat_messages;
-- alter publication supabase_realtime add table public.messages;
