
-- 1. 更新宠物表，增加发布者 ID 和联系方式
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id);
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS contact TEXT;

-- 允许用户修改和删除自己的宠物信息
DROP POLICY IF EXISTS "Allow users to update their own pets" ON public.pets;
CREATE POLICY "Allow users to update their own pets"
ON public.pets
FOR UPDATE
TO authenticated
USING (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Allow users to delete their own pets" ON public.pets;
CREATE POLICY "Allow users to delete their own pets"
ON public.pets
FOR DELETE
TO authenticated
USING (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Allow authenticated users to insert pets" ON public.pets;
CREATE POLICY "Allow authenticated users to insert pets"
ON public.pets
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = owner_id);

-- 2. 创建收藏表 (如果不存在)
CREATE TABLE IF NOT EXISTS public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  pet_id BIGINT REFERENCES public.pets(id) ON DELETE CASCADE NOT NULL,
  UNIQUE(user_id, pet_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow users to manage their own favorites" ON public.favorites;
CREATE POLICY "Allow users to manage their own favorites"
ON public.favorites
FOR ALL
TO authenticated
USING (auth.uid() = user_id);

-- 3. 创建申请表 (如果不存在)
CREATE TABLE IF NOT EXISTS public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  pet_id BIGINT REFERENCES public.pets(id) ON DELETE CASCADE NOT NULL,
  message TEXT,
  contact_info TEXT,
  status TEXT DEFAULT 'pending'
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow users to manage their own applications" ON public.applications;
CREATE POLICY "Allow users to manage their own applications"
ON public.applications
FOR ALL
TO authenticated
USING (auth.uid() = user_id);

-- 4. 创建交流中心表
CREATE TABLE IF NOT EXISTS public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  user_email TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read community_posts" ON public.community_posts;
CREATE POLICY "Allow public read community_posts"
ON public.community_posts
FOR SELECT
TO public
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert community_posts" ON public.community_posts;
CREATE POLICY "Allow authenticated users to insert community_posts"
ON public.community_posts
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to delete their own community_posts" ON public.community_posts;
CREATE POLICY "Allow users to delete their own community_posts"
ON public.community_posts
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
