-- 1. 通知系统表 (notifications)
create table public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  type text not null, -- 'system', 'message', 'adoption_update'
  title text not null,
  content text not null,
  is_read boolean default false,
  link text -- 可选跳转链接
);

-- 开启 RLS
alter table public.notifications enable row level security;

-- 策略：用户只能查看自己的通知
create policy "Users can view own notifications" on public.notifications
for select using (auth.uid() = user_id);

-- 策略：仅系统或触发者可以插入通知 (目前简化为认证用户可插入，实际应由后端或 Trigger 控制)
create policy "Authenticated users can insert notifications" on public.notifications
for insert with check (auth.role() = 'authenticated');

-- 策略：用户可以更新自己的通知 (标记已读)
create policy "Users can update own notifications" on public.notifications
for update using (auth.uid() = user_id);


-- 2. 宠物健康档案表 (health_records)
create table public.health_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pet_id bigint references public.pets on delete cascade not null,
  record_date date not null,
  type text not null, -- 'vaccine' (疫苗), 'checkup' (体检), 'surgery' (手术), 'other'
  title text not null,
  description text,
  vet_name text, -- 兽医/医院名称
  next_due_date date -- 下次预约时间
);

-- 开启 RLS
alter table public.health_records enable row level security;

-- 策略：所有人可以查看健康档案 (公开透明)
create policy "Public can view health records" on public.health_records
for select using (true);

-- 策略：仅宠物主人或管理员可以添加/修改记录
-- 这里假设宠物主人是 pet_id 对应的 owner_id，需要 join 查询，Supabase RLS 支持
-- 简化版：允许认证用户添加 (实际项目应更严格)
create policy "Authenticated users can manage health records" on public.health_records
for all using (auth.role() = 'authenticated');

-- 插入一些示例通知数据
-- insert into public.notifications (user_id, type, title, content) values ...
