
-- 创建宠物表
create table public.pets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null, -- '狗狗' | '猫咪' | '小兔'
  breed text not null,
  age text not null,
  image text not null,
  description text not null,
  tags text[] not null
);

-- 开启行级安全策略 (RLS)
alter table public.pets enable row level security;

-- 创建策略：允许所有人读取数据
create policy "Allow public read access"
on public.pets
for select
to public
using (true);

-- 插入初始数据 (从 Mock 数据迁移)
insert into public.pets (name, type, breed, age, image, description, tags)
values
  ('贝拉 (Bella)', '狗狗', '金毛寻回犬', '2 岁', 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80', '贝拉是一只非常友好且精力充沛的金毛犬，最喜欢玩接球游戏。', ARRAY['友好', '精力充沛', '亲近小孩']),
  ('露娜 (Luna)', '猫咪', '暹罗猫', '1 岁', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=600&q=80', '露娜是一只安静且粘人的暹罗猫，喜欢蜷缩在主人怀里。', ARRAY['安静', '粘人', '室内型']),
  ('查理 (Charlie)', '狗狗', '比格犬', '3 岁', 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=600&q=80', '查理是一只充满好奇心的比格犬，热爱户外探险。', ARRAY['好奇心强', '爱户外', '贪玩']),
  ('米洛 (Milo)', '猫咪', '虎斑猫', '6 个月', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80', '米洛是一只活泼的小猫，总是能给自己找到新鲜乐子。', ARRAY['活泼', '幼猫', '好奇']),
  ('黛西 (Daisy)', '小兔', '荷兰垂耳兔', '1 岁', 'https://images.unsplash.com/photo-1585110396063-7eb2555776d3?auto=format&fit=crop&w=600&q=80', '黛西是一只温柔的兔子，喜欢吃胡萝卜和享受安静时光。', ARRAY['温柔', '安静', '体型小']),
  ('马克斯 (Max)', '狗狗', '德国牧羊犬', '4 岁', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=600&q=80', '马克斯是一只忠诚且具有保护欲的伙伴，经过了良好的训练。', ARRAY['忠诚', '保护欲', '训练有素']);
